using SocialMedia.Core.Entities;
using System;
using System.Collections.Generic;

namespace SocialMedia.Core.DTOs
{
    public class PostDto
    {
        /// <summary>
        /// Autogenerated id for Post entity
        /// </summary>
        public int Id { get; set; }
        public int UserId { get; set; }
        public DateTime? Date { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public ImageFIle? Image { get; set; }
        public bool IsEdit { get; set; }
        public int Likes { get; set; }
        public string? Categories { get; set; }


        public virtual UserDto User { get; set; }
        public virtual ICollection<CommentDto> Comments { get; set; }
    }

    public class ImageFIle
    {
        public string Src { get; set; }
        public string Name { get; set; }

    }
}
