using SocialMedia.Core.Entities;
using System;
using System.Collections.Generic;

namespace SocialMedia.Core.DTOs
{
    public class PostDto
    {
        /// <summary>
        /// Autogenerated id for Post entity
        /// </summary>
        public int Id { get; set; }
        public int UserId { get; set; }
        public DateTime? Date { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int Likes { get; set; }

        public virtual UserDto User { get; set; }
        public virtual ICollection<CommentDto> Comments { get; set; }
    }
}
